// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	third "gitlab.qiniu.io/qbox/eden/cmd/demo/3rd/outside/handler/third"
	"gitlab.qiniu.io/qbox/eden/cmd/demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{{.routesAdditions}}
}
