// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"{{if .hasTimeout}}
	"time"{{end}}

	{{.importPackages}}
)

func RegisterHandlers(r *gin.RouterGroup,, serverCtx *svc.ServiceContext) {
	{{.routesAdditions}}
}
